# Generated by Django 4.2.7 on 2025-10-04 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="ocr_images/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("raw_text", models.TextField(blank=True, null=True)),
                (
                    "extracted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "extracted_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("extracted_date", models.DateField(blank=True, null=True)),
                (
                    "extracted_merchant",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("amount_confidence", models.FloatField(blank=True, null=True)),
                ("date_confidence", models.FloatField(blank=True, null=True)),
                ("merchant_confidence", models.FloatField(blank=True, null=True)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
