# Generated by Django 4.2.7 on 2025-10-04 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseapproval",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expenseapproval",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="expenses.expense",
            ),
        ),
        migrations.AddField(
            model_name="expenseapproval",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="approvals.approvalstep",
            ),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="approvals.approvalflow",
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Categories this rule applies to (empty = all categories)",
                to="expenses.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_rules",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="specific_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specific_approval_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalflow",
            name="approval_rules",
            field=models.ManyToManyField(
                blank=True, related_name="flows", to="approvals.approvalrule"
            ),
        ),
        migrations.AddField(
            model_name="approvalflow",
            name="categories",
            field=models.ManyToManyField(blank=True, to="expenses.expensecategory"),
        ),
        migrations.AddField(
            model_name="approvalflow",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_flows",
                to="companies.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="expenseapproval",
            unique_together={("expense", "approver")},
        ),
        migrations.AlterUniqueTogether(
            name="approvalstep",
            unique_together={("flow", "step_number")},
        ),
    ]
